### ISSUE TITLE
[PE-D][Tester D] Name of App in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-4/tp#136] opened 2024-04-05 18:56 UTC
The name at the top of the user guide PDF is still "AB3". Was that intentional? I recommend changing it to your app name, "Match".
![Screen Shot 2024-04-05 at 4.46.25 pm.png](https://raw.githubusercontent.com/myang2020/ped/main/files/ce3e6bd6-31f2-43bb-8fa0-99ae16a975bb.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: myang2020/ped#6

**Comment by SimKianSeng** [comment] 2024-04-08 03:32
duplicate of #163

**Closed by SimKianSeng** 2024-04-08 03:32 UTC
Labels: bug.GoodToFix, bug.Duplicate
